# Generated by Django 4.1.1 on 2022-10-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_topping_pizza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='equipment',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(to='store.topping'),
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='System',
        ),
    ]
