# Generated by Django 4.1.1 on 2022-10-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_system_equipment_alter_pizza_toppings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='pizzas', to='store.topping'),
        ),
    ]
