# Generated by Django 4.1.1 on 2022-10-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_pizza_toppings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.AddField(
            model_name='topping',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='pizzas', to='store.pizza'),
        ),
    ]
