# Generated by Django 4.1.1 on 2022-10-06 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_empleado_habilidades_delete_pizza_delete_topping_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['-first_name', 'last_name'], 'verbose_name': 'Mi Empleado', 'verbose_name_plural': 'Empleados de la empresa'},
        ),
        migrations.RenameField(
            model_name='habilidades',
            old_name='habilidad',
            new_name='hablidad',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='Habilidades',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('0', 'CONTADOR'), ('1', 'ADMINISTRADOR'), ('2', 'ECONOMISTA'), ('3', 'OTRO')], max_length=1, verbose_name='Trabajo'),
        ),
        migrations.CreateModel(
            name='HabilidadEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='descripcion')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.empleado')),
                ('habilidades', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.habilidades')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='habilidades',
            field=models.ManyToManyField(blank=True, through='store.HabilidadEmpleado', to='store.habilidades'),
        ),
    ]
