# Generated by Django 4.1.1 on 2022-10-06 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='material',
            new_name='nombre_material',
        ),
    ]
