# Generated by Django 4.1.1 on 2022-10-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_rename_material_material_nombre_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficios', models.CharField(max_length=75, verbose_name='Beneficios')),
            ],
        ),
    ]
