# Generated by Django 4.1.1 on 2022-10-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_subcategoria_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoria',
            name='nombre_sub_categoria',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
