# Generated by Django 4.1.1 on 2022-10-06 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_subcategoria_nombre_sub_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='categoria',
            new_name='nombre_categoria',
        ),
    ]
