# Generated by Django 4.1.1 on 2022-10-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_subcategoria_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre_categoria',
            field=models.CharField(max_length=75, verbose_name='noimbre de la cantegoria del producto'),
        ),
    ]
