# Generated by Django 4.1.1 on 2022-10-07 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_categoria_nombre_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['-nombre_categoria'], 'verbose_name': 'Categoria plantas', 'verbose_name_plural': 'Categorias y subcategorias de plantas'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre_categoria',
            field=models.CharField(max_length=75, verbose_name='nombre de la cantegoria del producto'),
        ),
        migrations.CreateModel(
            name='plantas_final',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_planta', models.CharField(max_length=100, verbose_name='Nombre')),
                ('colgante_no_colgante', models.CharField(choices=[('0', 'INTERIOR'), ('1', 'EXTERIOR'), ('2', 'AMBOS')], max_length=1, verbose_name='Eleccion')),
                ('precio', models.FloatField(null=True)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
                ('imagen_portada', models.ImageField(null=True, upload_to='imagenes_portada/', verbose_name='Imagen')),
                ('sub_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.subcategoria', verbose_name='categoria')),
            ],
        ),
    ]
