# Generated by Django 4.1.1 on 2022-10-07 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_plantas_final_colgante_no_colgante'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantas_final',
            name='interior_no_interior',
            field=models.CharField(choices=[('0', 'INTERIOR'), ('1', 'EXTERIOR'), ('2', 'AMBOS')], default=3, max_length=1, verbose_name='Interior o no exterior'),
            preserve_default=False,
        ),
    ]
