# Generated by Django 4.1.1 on 2022-10-07 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_plantas_final_interior_no_interior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantas_final',
            name='nombre_planta',
            field=models.CharField(max_length=100, verbose_name='nombre_planta'),
        ),
    ]
