# Generated by Django 4.1.1 on 2022-10-10 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_planta_beneficio_plantas_final_beneficios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planta_recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.plantas_final')),
                ('recomendacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.recomendaciones')),
            ],
        ),
        migrations.AddField(
            model_name='plantas_final',
            name='recomendaciones',
            field=models.ManyToManyField(blank=True, through='store.Planta_recomendacion', to='store.recomendaciones'),
        ),
    ]
