# Generated by Django 4.1.1 on 2022-10-10 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_planta_recomendacion_plantas_final_recomendaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planta_cuidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuidados', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.cuidados')),
                ('plantas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.plantas_final')),
            ],
        ),
        migrations.AddField(
            model_name='plantas_final',
            name='cuidados',
            field=models.ManyToManyField(blank=True, through='store.Planta_cuidado', to='store.cuidados'),
        ),
    ]
