# Generated by Django 4.1.1 on 2022-10-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_rename_cuidados_planta_cuidado_cuidado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos_plantas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes_plantas/', verbose_name='Imagen')),
            ],
        ),
    ]
