# Generated by Django 4.1.1 on 2022-10-10 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_fotos_plantas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planta_foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotos_plantas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.fotos_plantas')),
                ('plantas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.plantas_final')),
            ],
        ),
    ]
