# Generated by Django 4.1.1 on 2022-10-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_planta_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotos_plantas',
            old_name='imagen',
            new_name='foto',
        ),
        migrations.AlterField(
            model_name='plantas_final',
            name='cuidados',
            field=models.ManyToManyField(blank=True, through='store.Planta_foto', to='store.fotos_plantas'),
        ),
    ]
