# Generated by Django 4.1.1 on 2022-10-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_rename_imagen_fotos_plantas_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos_plantas',
            name='foto',
            field=models.ImageField(null=True, upload_to='imagenes_plantas/', verbose_name='Foto'),
        ),
    ]
