# Generated by Django 4.1.1 on 2022-10-10 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_alter_fotos_plantas_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planta_foto',
            old_name='fotos_plantas',
            new_name='foto',
        ),
    ]
