# Generated by Django 4.1.1 on 2022-10-10 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_rename_fotos_plantas_planta_foto_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotos_plantas',
            old_name='foto',
            new_name='fotos',
        ),
    ]
