# Generated by Django 4.1.1 on 2022-10-10 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_rename_foto_fotos_plantas_fotos'),
    ]

    operations = [
        migrations.CreateModel(
            name='macetas_final',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_maceta', models.CharField(max_length=100, verbose_name='nombre_maceta')),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
                ('precio', models.FloatField(null=True)),
                ('imagen_portada', models.ImageField(null=True, upload_to='imagenes_portada_maceta/', verbose_name='Imagen')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.subcategoria', verbose_name='material de maceta')),
            ],
        ),
    ]
