# Generated by Django 4.1.1 on 2022-10-10 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_alter_macetas_final_id_alter_macetas_final_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color',
            new_name='colores',
        ),
        migrations.CreateModel(
            name='Maceta_color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.color')),
                ('macetas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.macetas_final')),
            ],
        ),
        migrations.AddField(
            model_name='macetas_final',
            name='colores',
            field=models.ManyToManyField(blank=True, through='store.Maceta_color', to='store.color'),
        ),
    ]
