# Generated by Django 4.1.1 on 2022-10-10 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_rename_color_color_colores_maceta_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planta_color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.color')),
                ('plantas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.plantas_final')),
            ],
        ),
        migrations.AddField(
            model_name='plantas_final',
            name='colores',
            field=models.ManyToManyField(blank=True, through='store.Planta_color', to='store.color'),
        ),
    ]
