# Generated by Django 4.1.1 on 2022-10-10 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_planta_color_plantas_final_colores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos_macetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotos', models.ImageField(null=True, upload_to='imagenes_macetas/', verbose_name='Foto')),
            ],
        ),
        migrations.AddField(
            model_name='plantas_final',
            name='fotos',
            field=models.ManyToManyField(blank=True, through='store.Planta_foto', to='store.fotos_plantas'),
        ),
        migrations.AlterField(
            model_name='plantas_final',
            name='cuidados',
            field=models.ManyToManyField(blank=True, through='store.Planta_cuidado', to='store.cuidados'),
        ),
        migrations.CreateModel(
            name='Maceta_foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.fotos_macetas')),
                ('plantas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.macetas_final')),
            ],
        ),
    ]
