# Generated by Django 4.1.1 on 2022-10-10 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_fotos_macetas_plantas_final_fotos_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maceta_foto',
        ),
    ]
