# Generated by Django 4.1.1 on 2022-10-11 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_rename_plantas_maceta_foto_macetas'),
    ]

    operations = [
        migrations.AddField(
            model_name='macetas_final',
            name='foto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.fotos_macetas'),
        ),
    ]
