# Generated by Django 4.1.1 on 2022-10-11 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_macetas_final_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macetas_final',
            name='foto',
        ),
    ]
