# Generated by Django 4.1.1 on 2022-10-11 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_alter_fotos_macetas_fotos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macetas_final',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='plantas_final',
            name='cantidad',
        ),
    ]
