# Generated by Django 4.1.1 on 2022-10-11 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_remove_macetas_final_cantidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='plantas_macetas_final',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alto', models.FloatField(null=True)),
                ('ancho', models.FloatField(null=True)),
                ('largo', models.FloatField(null=True)),
                ('maceta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.macetas_final', verbose_name='Maceta del producto')),
                ('planta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.plantas_final', verbose_name='Planta del producto')),
            ],
        ),
    ]
