# Generated by Django 4.1.1 on 2022-10-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_plantas_macetas_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habilidadempleado',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='habilidadempleado',
            name='habilidades',
        ),
        migrations.AlterField(
            model_name='plantas_macetas_final',
            name='alto',
            field=models.FloatField(null=True, verbose_name='Alto de la maceta y planta juntas'),
        ),
        migrations.AlterField(
            model_name='plantas_macetas_final',
            name='ancho',
            field=models.FloatField(null=True, verbose_name='Ancho de la maceta y planta junta'),
        ),
        migrations.AlterField(
            model_name='plantas_macetas_final',
            name='largo',
            field=models.FloatField(null=True, verbose_name='Largo de la maceta y planta junta'),
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='HabilidadEmpleado',
        ),
        migrations.DeleteModel(
            name='Habilidades',
        ),
    ]
